#=====================================================================================
# Project			: Study_Class
# Description		: Build a C++ project "Study_Class"
# ------------------------------------------------------------------------------------
# File name			: Makefile
# Description		: The build script to manage & build the project "Study_Class".
# Creator			: XU ZAN
# Creation date		: Thur.		Nov. 27, 2014
# Copyright(C)		2014	All rights reserved.
# 
#=====================================================================================


Study_Class : Study_Class_Main.o Test.o

Study_Class_Main.o : Study_Class_Main.cpp Test.h
	g++ -c Study_Class_Main.cpp
